### ISSUE TITLE
Unable to render

### ISSUE THREAD

**Issue by pinoinside** [d3plus/d3plus-priestley#74]
I tried to import this library in my project but I do not find a way to render the Priestley timeline.
That's the code I used:
<script src="https://cdn.jsdelivr.net/npm/d3plus@2.1.3/build/d3plus.full.min.js"></script>
	<script>
	  console.log(d3plus);
	  var data = [
		  {id: "alpha",   start: 2004, end: 2007},
		  {id: "epsilon", start: 2007, end: 2012},
		  {id: "beta",    start: 2005, end: 2010},
		];
		new d3plus.Priestley()
		  .data(data)
		  .render();
	</script>
I feel like I miss something, like "where" the timeline must be rendered but I do not know how to do it.
Thanks in advance.

Andrea

**Comment by davelandry** [comment]
@pinoinside by default, d3plus will create a new `<div>` at the bottom of the `<body>` element to house the viz. If you have a page with more content than just the viz, and want it to render inside of a specific element, you need to use the `select` method to choose which element you would like to use. Here is a full HTML example that shows this behavior, let me know if this still doesn't work for you:

```html
<!doctype html>
<html>

<head>

  <meta charset="utf-8">
  <script src="https://cdn.jsdelivr.net/npm/d3plus@2.1.3/build/d3plus.full.min.js"></script>

</head>

<body>

  <div id="myViz"></div>

</body>

<script>

  var data = [
    {id: "alpha",   start: 2004, end: 2007},
    {id: "epsilon", start: 2007, end: 2012},
    {id: "beta",    start: 2005, end: 2010},
  ];

  new d3plus.Priestley()
    .data(data)
    .select("#myViz")
    .render();

</script>

</html>
```
